datasets:
  mimic_caption: # name of the dataset builder
    data_type: images # [images|videos|features] we use features in this case for extracted video features

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      images:
          storage: /media/tianyu.han/mri-scratch/DeepLearning/Stanford_MIT_CHEST/MIMIC-CXR-v2.0/mimic-cxr/
      annotations:
        train:
          storage: /media/tianyu.han/mri-scratch/DeepLearning/flamingo-mini/data/mimic_impressions.csv
          column: findings
        val:
          storage: /media/tianyu.han/mri-scratch/DeepLearning/flamingo-mini/data/mimic_impressions_val.csv
          column: findings
